name: SupertMarketApi CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Publish
        run: dotnet publish -c Release
      - name: Archive Deploy Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-deploy-artifacts
          path: |
            SuperMarketApi/bin/Release/netcoreapp3.1/publish
            SuperMarketApi/Dockerfile
  
  dockerize:
    runs-on: ubuntu-latest
    needs: build_test
    env:
      IMAGE_TAG: "${{ secrets.REGISTRY_LOGIN_SERVER }}/supermarket-api:${{ github.sha }}"
    steps:
      - name: Download Deploy Artifacts
        uses: actions/download-artifact@v2
        with:
          name: app-deploy-artifacts
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ env.IMAGE_TAG }}
          docker push ${{ env.IMAGE_TAG }}

      
