name: SupertMarketApi CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Publish
        run: dotnet publish -c Release
      - name: Archive Deploy Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-deploy-artifacts
          path: |
            SuperMarketApi/bin/Release/netcoreapp3.1/publish
            SuperMarketApi/Dockerfile
  
  dockerize:
    runs-on: ubuntu-latest
    needs: build_test
    env:
      IMAGE_TAG: "supermarket/api:version${{ github.run_id }}"
    steps:
      - name: Download Deploy Artifacts
        uses: actions/download-artifact@v2
        with:
          name: app-deploy-artifacts
      - name: Docker
        run: |
          echo Building docker image with tag = ${{ IMAGE_TAG }}
          docker build -t ${{ IMAGE_TAG }} .

      
