name: SupertMarketApi CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Build
        run: dotnet build --no-restore
  
  dockerize:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
      - name: Docker
        run: echo "TODO - Dockerize"
      
